/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/alert/Alert.vue')['default']
    Button: typeof import('./src/components/button/Button.vue')['default']
    Cascade: typeof import('./src/components/cascade/Cascade.vue')['default']
    ColorDrop: typeof import('./src/components/tag-status-item/ColorDrop.vue')['default']
    Dropdown: typeof import('./src/components/dropdown/Dropdown.vue')['default']
    DropdownItem: typeof import('./src/components/dropdown-item/DropdownItem.vue')['default']
    DropdownMenu: typeof import('./src/components/dropdown-menu/DropdownMenu.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascade: typeof import('element-plus/es')['ElCascade']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Info: typeof import('./src/components/protective-footer/info.vue')['default']
    InvitationDialog: typeof import('./src/components/invitation-dialog/index.vue')['default']
    MemberAvatar: typeof import('./src/components/member-avatar/index.vue')['default']
    OInput: typeof import('./src/components/input/OInput.vue')['default']
    ProtectiveFooter: typeof import('./src/components/protective-footer/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/select/index.vue')['default']
    SvgIcon: typeof import('./src/components/svg-icon/index.vue')['default']
    TagStatusItem: typeof import('./src/components/tag-status-item/index.vue')['default']
    TestPop: typeof import('./src/components/test-pop/index.vue')['default']
    Text: typeof import('./src/components/text/index.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Timeline: typeof import('./src/components/timeline/Timeline.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
