/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/alert/Alert.vue')['default']
    Button: typeof import('./src/components/button/Button.vue')['default']
    ColorDrop: typeof import('./src/components/tag-status-item/ColorDrop.vue')['default']
    Dropdown: typeof import('./src/components/dropdown/Dropdown.vue')['default']
    DropdownItem: typeof import('./src/components/dropdown-item/DropdownItem.vue')['default']
    DropdownMenu: typeof import('./src/components/dropdown-menu/DropdownMenu.vue')['default']
    MemberAvatar: typeof import('./src/components/member-avatar/index.vue')['default']
    OInput: typeof import('./src/components/input/OInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/select/index.vue')['default']
    SvgIcon: typeof import('./src/components/svg-icon/index.vue')['default']
    TagStatusItem: typeof import('./src/components/tag-status-item/index.vue')['default']
    Text: typeof import('./src/components/text/index.vue')['default']
    Timeline: typeof import('./src/components/timeline/Timeline.vue')['default']
  }
}
